### ISSUE TITLE
stream shall be created only once during prepare

### ISSUE THREAD

**Issue by MatiasVara** [virtio-sound/vhost-device#22]
Stream shall be created only during transiting from SET_PARAM to PREPARE in the prepare() cmd. Otherwise, we are creating several streams, each time guest triggers the prepare() cmd. See https://github.com/virtio-sound/vhost-device/blob/d2757aea471822329ce263c1f9fe740278ed5a0f/crates/sound/src/audio_backends/pw_backend.rs#L275

**Comment by dorindabassey** [comment]
I thought that the best approach was to add a pw_stream_destroy bindings, because using a Drop impl makes the stream destroy itself automatically as soon as the first one is dropped, even though the "real" Stream wrapper is still being used, but that's apparently not the best approach aswell, Since adding the pw_stream_destroy bindings results in some segfault. The other workaround would have been to  create the stream on the condition that the stream has not been created yet, But the condition  blocks the usage of stream in the stream_listener.

**Comment by MatiasVara** [comment]
> The other workaround would have been to create the stream on the condition that the stream has not been created yet, But the condition blocks the usage of stream in the stream_listener.

Could you elaborate on this?

**Comment by MatiasVara** [comment]
I close this issue since this is tracked at #43.
